#!/bin/sh
# Xcode Cloud: Configuration/Secrets.xcconfig is gitignored, so build it from
# the workflow's environment variables (set them under Workflow > Environment).
set -eu
cd "$(dirname "$0")/.."
if [ -z "${BUG_REPORT_INGEST_KEY:-}" ] || [ -z "${BUG_REPORT_HOST:-}" ]; then
  echo "error: BUG_REPORT_INGEST_KEY and BUG_REPORT_HOST must be set in the Xcode Cloud workflow environment." >&2
  exit 1
fi
cat > Configuration/Secrets.xcconfig <<XC
// Generated by ci_scripts/ci_post_clone.sh on Xcode Cloud.
BUG_REPORT_INGEST_KEY = $BUG_REPORT_INGEST_KEY
BUG_REPORT_HOST = $BUG_REPORT_HOST
XC
echo "Wrote Configuration/Secrets.xcconfig for host $BUG_REPORT_HOST"
