import Testing
@testable import JaneyGames

/// Parity vectors generated by running the mulberry32 implementation in
/// web/shared/engine.js under Node — the Swift port must match bit-exactly.
struct SeedEngineTests {
    @Test(arguments: [
        (0, [0.26642920868471265, 0.0003297457005828619, 0.2232720274478197, 0.1462021479383111,
             0.46732782293111086, 0.5450490827206522, 0.6152513844426721, 0.6489853798411787]),
        (1, [0.6270739405881613, 0.002735721180215478, 0.5274470399599522, 0.9810509674716741,
             0.9683778982143849, 0.281103502959013, 0.6128388606011868, 0.7207431411370635]),
        (42, [0.6011037519201636, 0.44829055899754167, 0.8524657934904099, 0.6697340414393693,
              0.17481389874592423, 0.5265925421845168, 0.2732279943302274, 0.6247446539346129]),
        (20_260_821, [0.7162383929826319, 0.8401872285176069, 0.005741450237110257, 0.587558510247618,
                      0.005740602733567357, 0.6638553000520915, 0.484648107085377, 0.292649106355384]),
        (-7, [0.43306733411736786, 0.32539576734416187, 0.5442695003002882, 0.48018999374471605,
              0.048719558166339993, 0.041189806535840034, 0.2679634625092149, 0.20619804575107992]),
        (2_147_483_647, [0.4290980885270983, 0.12713524978607893, 0.3852774982806295, 0.39639189024455845,
                         0.11962746665813029, 0.9531875969842076, 0.6806830384302884, 0.9957805015146732]),
    ] as [(Int, [Double])])
    func nextMatchesJavaScript(seed: Int, expected: [Double]) {
        var engine = SeedEngine(seed: seed)
        for value in expected {
            #expect(engine.next() == value)
        }
    }

    @Test(arguments: [
        (0, [26, 0, 22, 14, 46, 54, 61, 64]),
        (42, [60, 44, 85, 66, 17, 52, 27, 62]),
        (-7, [43, 32, 54, 48, 4, 4, 26, 20]),
    ] as [(Int, [Int])])
    func nextIntMatchesJavaScript(seed: Int, expected: [Int]) {
        var engine = SeedEngine(seed: seed)
        for value in expected {
            #expect(engine.nextInt(100) == value)
        }
    }

    @Test(arguments: [
        (0, [3, 8, 6, 4, 5, 9, 7, 1, 0, 2]),
        (1, [7, 8, 3, 2, 1, 5, 9, 4, 0, 6]),
        (42, [0, 7, 3, 5, 2, 1, 8, 9, 4, 6]),
        (20_260_821, [2, 6, 5, 1, 3, 8, 4, 0, 9, 7]),
        (-7, [8, 6, 7, 1, 5, 0, 3, 9, 2, 4]),
        (2_147_483_647, [8, 5, 7, 6, 9, 0, 2, 3, 1, 4]),
    ] as [(Int, [Int])])
    func shuffleMatchesJavaScript(seed: Int, expected: [Int]) {
        var engine = SeedEngine(seed: seed)
        #expect(engine.shuffle(Array(0...9)) == expected)
    }

    @Test
    func valuesStayInUnitInterval() {
        var engine = SeedEngine(seed: 123_456)
        for _ in 0..<10_000 {
            let value = engine.next()
            #expect(value >= 0 && value < 1)
        }
    }
}
